name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'lib/*.ts'
  pull_request:
    branches:
      - main
    paths:
      - 'lib/*.ts'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM install
        run: npm ci

      - name: Run test
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: weiliddat/twired
